### ISSUE TITLE
[CONTRIBUTION]: Work on table Contact

### ISSUE THREAD

**Issue by AbhijithGanesh** [CodXCrypt/Exam-Portal#7]
Work on the table contacts ,  according to Database Schema:

- [ ] Name
- [ ] Contact Number
- [ ] Email
- [ ] Reference it to Teacher
- [ ] Reference it to Student

**Comment by Anik-Bardhan** [comment]
@AbhijithGanesh can I be assigned to this?

**Comment by AbhijithGanesh** [comment]
Would you like to work on the student table first? then this ?It'd be more effective this way IMO @Anik-Bardhan

**Comment by Anik-Bardhan** [comment]
@AbhijithGanesh okay. Assign me to it then.

**Comment by AbhijithGanesh** [comment]
Can you request in the issue link #6

**Comment by AbhijithGanesh** [comment]
Please don't create UUID field, It is not necessary
